name: Release Nuget Package

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    working-directory: ./XamExtensionsSvg

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./XamExtensionsSvg
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Setup nuget
        uses: nuget/setup-nuget@v1
      - name: Restore nuget packages for solution
        run: nuget restore ../XamExtensionsSvg.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build
        run: msbuild XamExtensionsSvg.csproj /property:Configuration=Release
      - name: Pack
        run: |
          $version=${{ steps.tag.outputs.result }}
          $version=$version.replace("refs/tags/v", "")
          nuget pack XamExtensionsSvg.nuspec -Prop Configuration=Release -verbosity detailed -basepath ./ -OutputDirectory ./package -Version $version
      - name: Setup Nuget Push
        run: nuget setApiKey "$env:NUGET_ORG_TOKEN"
        env:
          NUGET_ORG_TOKEN: ${{ secrets.NUGET_ORG_TOKEN }}
      - name: Push
        run: |
          $version=${{ steps.tag.outputs.result }}
          $version=$version.replace("refs/tags/v", "")
          $package="package/Xamarin.Forms.Extensions.Svg." + $version + ".nupkg"
          nuget push $package -Source https://api.nuget.org/v3/index.json